version: '3.3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    image: logo-study-assistant
    depends_on:
      - postgres
    volumes:
      - .:/app
    env_file:
      - .env
      - .env.db
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000

  postgres:
    image: postgres:13.4
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    env_file:
      - .env.db
